/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import java.sql.Connection;



/**
 *
 * @author Admin
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmPersonas = new javax.swing.JMenuItem();
        jmAgencias = new javax.swing.JMenuItem();
        jmEstudios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jmAcercade = new javax.swing.JMenu();
        MenuConsultaPersona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738087_personal.png"))); // NOI18N
        jButton1.setToolTipText("Nuevo Persona");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738087_consulta_persona.png"))); // NOI18N
        jButton2.setToolTipText("Consulta Persona");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738232_office-building.png"))); // NOI18N
        jButton3.setToolTipText("Nuevo Agencia");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738232_consulta_agencia.png"))); // NOI18N
        jButton4.setToolTipText("Consulta Agencia");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738276_tests.png"))); // NOI18N
        jButton5.setToolTipText("Nuevo Estudio");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738276_consulta_estudio.png"))); // NOI18N
        jButton6.setToolTipText("Consulta Estudio");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jMenu1.setText("Nuevo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmPersonas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738087_personal.png"))); // NOI18N
        jmPersonas.setText("Personas");
        jmPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPersonasActionPerformed(evt);
            }
        });
        jMenu1.add(jmPersonas);

        jmAgencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmAgencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738232_office-building.png"))); // NOI18N
        jmAgencias.setText("Agencias");
        jmAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgenciasActionPerformed(evt);
            }
        });
        jMenu1.add(jmAgencias);

        jmEstudios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmEstudios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738276_tests.png"))); // NOI18N
        jmEstudios.setText("Estudios");
        jmEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstudiosActionPerformed(evt);
            }
        });
        jMenu1.add(jmEstudios);
        jMenu1.add(jSeparator1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456739001_Delete.png"))); // NOI18N
        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jmAcercade.setText("Consulta");
        jmAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAcercadeActionPerformed(evt);
            }
        });

        MenuConsultaPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1456738087_consulta_persona.png"))); // NOI18N
        MenuConsultaPersona.setText("Personas");
        MenuConsultaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaPersonaActionPerformed(evt);
            }
        });
        jmAcercade.add(MenuConsultaPersona);

        jMenuBar1.add(jmAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPersonasActionPerformed
        // CODIGO PARA MOSTRAR LA VENTANA NUEVO PERSONAS.
        VNPersona nuevaPersona = new VNPersona();
        this.Escritorio.add(nuevaPersona);
        nuevaPersona.show();
    
    }//GEN-LAST:event_jmPersonasActionPerformed

    private void jmAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgenciasActionPerformed
        // CODIGO PARA MOSTRAR LA VENTANA NUEVO AGENCIAS:
        //VNAgencia nuevaAgencia = new VNAgencia();
        //this.Escritorio.add(nuevaAgencia);
        //nuevaAgencia.show();
    }//GEN-LAST:event_jmAgenciasActionPerformed

    private void jmEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstudiosActionPerformed
        // CODIGO PARA MOSTRAR LA VENTANA NUEVO ESTUDIOS
        //VNEstudio estudio = new VNEstudio();
        //this.Escritorio.add(estudio);
        //estudio.show();
    }//GEN-LAST:event_jmEstudiosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // CODDIGO PARA SALIR DEL PROGRAMA:
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jmAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAcercadeActionPerformed
        // CODIGO PARA MOSTRAR LA VENTANA ACERDA DE.
        //Acercade acerca = new Acercade();
        //this.Escritorio.add(acerca);
        //acerca.show();
    }//GEN-LAST:event_jmAcercadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // CODIGO PARA MOSTRAR LA VENTANA NUEVO PERSONAS.
        VNPersona nuevaPersona = new VNPersona();
        this.Escritorio.add(nuevaPersona);
        nuevaPersona.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // CODIGO PARA MOSTRAR LA VENTANA NUEVO AGENCIAS:
        //VNAgencia nuevaAgencia = new VNAgencia();
        //this.Escritorio.add(nuevaAgencia);
        //nuevaAgencia.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // CODIGO PARA MOSTRAR LA VENTANA NUEVO ESTUDIOS
        //VNEstudio estudio = new VNEstudio();
        //this.Escritorio.add(estudio);
        //estudio.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void MenuConsultaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaPersonaActionPerformed
        // CODIGO DE PRUEBA PARA VER EL FUNCIONAMIENTO DEL MENU.: 
        //JOptionPane.showMessageDialog(null,"Este es una ventana");
        VBPersona busquedaPersona = new VBPersona(this.Escritorio);
        this.Escritorio.add(busquedaPersona);
        busquedaPersona.show();
    }//GEN-LAST:event_MenuConsultaPersonaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VBPersona busquedaPersona = new VBPersona(this.Escritorio);
        this.Escritorio.add(busquedaPersona);
        busquedaPersona.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //CODIGO PARA QUE LA PANTALLA INICIE MAXIMIZADA
                menu men = new menu();
                men.setExtendedState(MAXIMIZED_BOTH);
                men.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MenuConsultaPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmAcercade;
    private javax.swing.JMenuItem jmAgencias;
    private javax.swing.JMenuItem jmEstudios;
    private javax.swing.JMenuItem jmPersonas;
    // End of variables declaration//GEN-END:variables

 /*   Conectar cc= new Conectar();
    Connection cn = cc.conexion();
*/
}
