/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorColonia;
import Controlador.ControladorPersona;
import Modelo.ColoniaVO;
import java.awt.event.ItemEvent;


/*
 * @author Admin
 */
public class VNPersona extends javax.swing.JInternalFrame {
ControladorPersona cPersona;
ControladorColonia cColonia;
int fila;
    
    /**
     * Creates new form Personas
     */
    public VNPersona() {
        initComponents();
        cPersona = new ControladorPersona();
        cColonia = new ControladorColonia();
        tablaPersonas.setModel(cPersona.seleccionarUltimasPersonas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MenuModificar = new javax.swing.JMenuItem();
        MenuEliminar = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtP_Apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtS_Apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTel_Fijo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTel_Movil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCod_Postal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFec_Nac = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNSE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rbtnCd_Mex = new javax.swing.JRadioButton();
        rbtnEdo_Mex = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnFemenino = new javax.swing.JRadioButton();
        comboColonia = new javax.swing.JComboBox<ColoniaVO>();
        jLabel20 = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        MenuModificar.setText("Modificar");
        MenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuModificar);

        MenuEliminar.setText("Eliminar");
        MenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuEliminar);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Nueva Persona");

        jLabel1.setText("Nombre(s) de la Persona:");

        jLabel2.setText("Primer Apellido:");

        txtP_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP_ApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Segundo Apellido:");

        jLabel4.setText("Teléfono Fijo:");

        jLabel5.setText("Teléfono Móvil:");

        jLabel6.setText("Correo Electrónico:");

        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaPersonas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tablaPersonas);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel7.setText("C. Postal:");

        txtCod_Postal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCod_PostalFocusLost(evt);
            }
        });
        txtCod_Postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_PostalActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha de Nacimiento:");

        jLabel9.setText("Dirección:");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Datos Generales");

        txtFec_Nac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFec_NacFocusLost(evt);
            }
        });

        jLabel12.setText("Edad:");

        txtEdad.setEditable(false);

        jLabel13.setText("Colonia:");

        jLabel14.setText("Municipio:");

        txtMunicipio.setEditable(false);

        jLabel15.setText("NSE:");

        txtNSE.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel16.setText("Datos de contacto");

        jLabel17.setText("Estado:");

        buttonGroup2.add(rbtnCd_Mex);
        rbtnCd_Mex.setText("CDMX");

        buttonGroup2.add(rbtnEdo_Mex);
        rbtnEdo_Mex.setText("Edo. Mex.");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel18.setText("Datos de Domicilio");

        jLabel19.setText("Genero:");

        buttonGroup1.add(rbtnMasculino);
        rbtnMasculino.setText("Masculino");

        buttonGroup1.add(rbtnFemenino);
        rbtnFemenino.setText("Femenino");

        comboColonia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboColoniaItemStateChanged(evt);
            }
        });
        comboColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColoniaActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel20.setText("Ultimos Registros ");

        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.setEnabled(false);
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtP_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnFemenino)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFec_Nac, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtS_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCod_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNSE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDireccion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnCd_Mex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnEdo_Mex))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel5)
                                .addGap(240, 240, 240)
                                .addComponent(txtMail))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar))
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTel_Fijo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(txtTel_Movil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtP_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtS_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rbtnMasculino)
                    .addComponent(rbtnFemenino)
                    .addComponent(jLabel8)
                    .addComponent(txtFec_Nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(comboColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtCod_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(rbtnEdo_Mex)
                    .addComponent(rbtnCd_Mex))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTel_Fijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTel_Movil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnGuardarCambios)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String genero;
        if(rbtnMasculino.isSelected()){
            genero = "0";
        }
        else{
            if(rbtnFemenino.isSelected()){
                genero = "1";
            }
            else{
                genero = "-1";
            }
        }
        cPersona.insertarPersona(txtNombre.getText(), txtP_Apellido.getText(), txtS_Apellido.getText(), genero, txtFec_Nac.getText(), txtDireccion.getText(), comboColonia.getSelectedItem(), txtTel_Fijo.getText(), txtTel_Movil.getText(), txtMail.getText());
        tablaPersonas.setModel(cPersona.seleccionarUltimasPersonas());
        
        txtNombre.setText("");
        txtP_Apellido.setText("");
        txtS_Apellido.setText("");
        buttonGroup1.clearSelection();
        txtFec_Nac.setText("");
        txtEdad.setText("");
        txtDireccion.setText("");
        txtCod_Postal.setText("");
        comboColonia.removeAllItems();
        txtNSE.setText("");
        txtMunicipio.setText("");
        buttonGroup2.clearSelection();
        txtTel_Fijo.setText("");
        txtTel_Movil.setText("");
        txtMail.setText("");
        rbtnEdo_Mex.setEnabled(true);
        rbtnCd_Mex.setEnabled(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void MenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuModificarActionPerformed
        fila = tablaPersonas.getSelectedRow();
        cPersona.mostrarPersona(tablaPersonas.getValueAt(fila, 0).toString(), txtNombre, txtP_Apellido, txtS_Apellido, rbtnMasculino, rbtnFemenino, txtFec_Nac, txtEdad, txtDireccion, txtCod_Postal, comboColonia, txtNSE, txtMunicipio, rbtnCd_Mex, rbtnEdo_Mex, txtTel_Fijo, txtTel_Movil, txtMail);
        btnGuardarCambios.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_MenuModificarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        fila = tablaPersonas.getSelectedRow();
        cPersona.mostrarPersona(tablaPersonas.getValueAt(fila, 0).toString(), txtNombre, txtP_Apellido, txtS_Apellido, rbtnMasculino, rbtnFemenino, txtFec_Nac, txtEdad, txtDireccion, txtCod_Postal, comboColonia, txtNSE, txtMunicipio, rbtnCd_Mex, rbtnEdo_Mex, txtTel_Fijo, txtTel_Movil, txtMail);
        btnGuardarCambios.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void MenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEliminarActionPerformed
        int fila = tablaPersonas.getSelectedRow();
        cPersona.eliminarPersona(tablaPersonas.getValueAt(fila, 0).toString());
        tablaPersonas.setModel(cPersona.seleccionarUltimasPersonas());
    }//GEN-LAST:event_MenuEliminarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaPersonas.getSelectedRow();
        cPersona.eliminarPersona(tablaPersonas.getValueAt(fila, 0).toString());
        tablaPersonas.setModel(cPersona.seleccionarUltimasPersonas());
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtP_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP_ApellidoActionPerformed

    private void txtCod_PostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_PostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_PostalActionPerformed

    private void txtCod_PostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCod_PostalFocusLost
        cColonia.getListaColonias(txtCod_Postal.getText(), comboColonia, txtNSE, txtMunicipio, rbtnCd_Mex, rbtnEdo_Mex);
    }//GEN-LAST:event_txtCod_PostalFocusLost

    private void comboColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColoniaActionPerformed
        
    }//GEN-LAST:event_comboColoniaActionPerformed

    private void comboColoniaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboColoniaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            cColonia.buildColoniaGUI(comboColonia.getSelectedItem(), txtNSE, txtMunicipio, rbtnCd_Mex, rbtnEdo_Mex);
        }
    }//GEN-LAST:event_comboColoniaItemStateChanged

    private void txtFec_NacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFec_NacFocusLost
        txtEdad.setText(cPersona.setEdadGUI(txtFec_Nac.getText()));
    }//GEN-LAST:event_txtFec_NacFocusLost

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        String genero;
        if(rbtnMasculino.isSelected()){
            genero = "0";
        }
        else{
            if(rbtnFemenino.isSelected()){
                genero = "1";
            }
            else{
                genero = "-1";
            }
        }
        
        cPersona.modificarPersonaTotal(tablaPersonas.getValueAt(fila, 0).toString(), txtNombre.getText(), txtP_Apellido.getText(), txtS_Apellido.getText(), genero, txtFec_Nac.getText(), txtDireccion.getText(), comboColonia.getSelectedItem(), txtTel_Fijo.getText(), txtTel_Movil.getText(), txtMail.getText());
        tablaPersonas.setModel(cPersona.seleccionarUltimasPersonas());
        
        txtNombre.setText("");
        txtP_Apellido.setText("");
        txtS_Apellido.setText("");
        buttonGroup1.clearSelection();
        txtFec_Nac.setText("");
        txtEdad.setText("");
        txtDireccion.setText("");
        txtCod_Postal.setText("");
        comboColonia.removeAllItems();
        txtNSE.setText("");
        txtMunicipio.setText("");
        buttonGroup2.clearSelection();
        txtTel_Fijo.setText("");
        txtTel_Movil.setText("");
        txtMail.setText("");
        rbtnEdo_Mex.setEnabled(true);
        rbtnCd_Mex.setEnabled(true);
        btnGuardarCambios.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtNombre.setText("");
        txtP_Apellido.setText("");
        txtS_Apellido.setText("");
        buttonGroup1.clearSelection();
        txtFec_Nac.setText("");
        txtEdad.setText("");
        txtDireccion.setText("");
        txtCod_Postal.setText("");
        comboColonia.removeAllItems();
        txtNSE.setText("");
        txtMunicipio.setText("");
        buttonGroup2.clearSelection();
        txtTel_Fijo.setText("");
        txtTel_Movil.setText("");
        txtMail.setText("");
        rbtnEdo_Mex.setEnabled(true);
        rbtnCd_Mex.setEnabled(true);
        btnGuardarCambios.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuEliminar;
    private javax.swing.JMenuItem MenuModificar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<ColoniaVO> comboColonia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnCd_Mex;
    private javax.swing.JRadioButton rbtnEdo_Mex;
    private javax.swing.JRadioButton rbtnFemenino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JTable tablaPersonas;
    private javax.swing.JTextField txtCod_Postal;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFec_Nac;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNSE;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtP_Apellido;
    private javax.swing.JTextField txtS_Apellido;
    private javax.swing.JTextField txtTel_Fijo;
    private javax.swing.JTextField txtTel_Movil;
    // End of variables declaration//GEN-END:variables
}

